---
title: "HowToBlog #1: setup work environment"
description: "tutorial to install and config needed software"
author: "Marcel Hanschmann"
date: "2024-01-11"
categories: [HowToBlog]
doi: xx.xxxx/xxxxxx
freeze: true
---

::: grid
::: {.g-col-12 .g-col-12-header}
**#1 Software**
:::

::: {.g-col-6 .g-col-6-body}
You will need:

-   git (<https://git-scm.com/downloads>)

-   R (<https://cran.r-project.org/>)

-   RStudio (<https://posit.co/download/rstudio-desktop/>)\<

-   RTools (<https://cran.r-project.org/bin/windows/Rtools/>)

-   Quarto (<https://quarto.org/docs/get-started/>)

download and install software. If you already have some of it, then make sure everything is the latest version.

When using Windows, install RStudio and RTools to C:\\

(default path: C:\\program files\\ may cause errors)
:::

::: g-col-6
:::
:::

::: grid
::: {.g-col-12 .g-col-12-header}
**#2 Config Github & RStudio**
:::

::: {.g-col-12 .g-col-12-sub}
in github: 
:::

::: {.g-col-6 .g-col-6-body}
- \> \> get invited to organisation and accept
- create pat in github, copy pat_string (save somewhere, because you can't see it in github later
:::

::: {.g-col-12 .g-col-12-sub}
in RStudio: 
:::

::: {.g-col-6 .g-col-6-body}
-   install needed packages
-   create new Project
    -   use version control and git
    -   paste git directory
-   set git name, email in terminal:
    -   git config --global user.email "your Email"
    -   git config --global user.name "Your Name"
    -   (omit "--global" to set only for current project
-   set PAT: in console: gitcreds::gitcreds_set(), than insert pat string
:::
:::
